import { expect, test, type Page } from '@playwright/test'

async function anonymous(page: Page) {
  await page.route('**/api/**', route => route.fulfill({ json: route.request().url().endsWith('/me') ? { kind: 'anonymous' } : { version: 'dev', status: 'idle' } }))
  page.on('pageerror', error => { throw error })
}

test('home links to public page beside Privacy; direct URL and home work without login', async ({ page }) => {
  await anonymous(page)
  await page.goto('/')
  const info = page.getByRole('navigation', { name: 'Informazioni su Recapp' })
  await expect(info.getByRole('link', { name: 'Privacy' })).toBeVisible()
  await info.getByRole('link', { name: 'FAQ e creatori' }).click()
  await expect(page).toHaveURL(/\/faq$/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('FAQ e creatori')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Domande frequenti' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Leo', exact: true })).toBeVisible()
  await expect(page.locator('.creator-slide[data-active="true"]')).toContainText('Developer e creatore')
  await page.getByRole('button', { name: 'Creatore successivo' }).click()
  await expect(page.getByRole('heading', { name: 'Luca', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Alex', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Alex', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Torna alla home' }).last().click()
  await expect(page).toHaveURL(/\/$/)
})

test('accordion expands by mouse and keyboard, keeps one open and can collapse', async ({ page }) => {
  await anonymous(page)
  await page.goto('/faq')
  const first = page.getByRole('button', { name: 'Che cos’è Recapp e a cosa serve?' })
  const second = page.getByRole('button', { name: 'Recapp è un servizio ufficiale della scuola?' })
  await expect(page.locator('.faq-answer[aria-hidden="false"]')).toHaveCount(0)
  await first.click()
  await expect(first).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('region', { name: 'Che cos’è Recapp e a cosa serve?' })).toContainText('riepiloghi')
  await second.focus()
  await page.keyboard.press('Enter')
  await expect(first).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('.faq-answer[aria-hidden="false"]')).toHaveCount(1)
  await page.keyboard.press('Space')
  await expect(second).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('.faq-answer[aria-hidden="false"]')).toHaveCount(0)
})

test('closed answers remove links from keyboard navigation and privacy link works', async ({ page }) => {
  await anonymous(page)
  await page.goto('/faq')
  const question = page.getByRole('button', { name: 'Come vengono utilizzati i dati e dove trovo l’informativa privacy?' })
  await expect(page.getByRole('link', { name: 'Privacy' })).toHaveCount(0)
  await question.click()
  const link = page.getByRole('link', { name: 'Privacy' })
  await expect(link).toBeVisible()
  await link.click()
  await expect(page).toHaveURL(/\/privacy$/)
})

for (const mobile of [false, true]) for (const dark of [false, true]) {
  test(`public page ${mobile ? 'mobile' : 'desktop'} ${dark ? 'dark' : 'light'}`, async ({ page }, testInfo) => {
    await page.setViewportSize(mobile ? { width: 360, height: 740 } : { width: 1280, height: 900 })
    await anonymous(page)
    await page.addInitScript(value => localStorage.setItem('ieri.theme', value), dark ? 'dark' : 'light')
    await page.goto('/faq')
    await page.getByRole('button', { name: 'Qual è la differenza tra demo e classe ufficiale?' }).click()
    const answer = page.locator('.faq-answer[data-open="true"]')
    await answer.evaluate(async element => { await Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished)) })
    expect(await answer.evaluate(element => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
    await expect(page.getByRole('heading', { name: 'Chi ha creato Recapp' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.locator('html')).toHaveClass(dark ? /dark/ : /^$/)
    await page.screenshot({ path: testInfo.outputPath(`faq-${mobile ? 'mobile' : 'desktop'}-${dark ? 'dark' : 'light'}.png`), fullPage: true })
  })
}

test('English and reduced motion keep all content usable', async ({ page }) => {
  await anonymous(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => localStorage.setItem('ieri.lang', 'en'))
  await page.goto('/faq')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('FAQ and creators')
  await page.getByRole('button', { name: 'What is Recapp and what is it for?' }).click()
  await expect(page.getByRole('region', { name: 'What is Recapp and what is it for?' })).toContainText('summaries')
  expect(await page.locator('.faq-answer').first().evaluate(el => parseFloat(getComputedStyle(el).transitionDuration))).toBeLessThanOrEqual(0.00001)
})

test('slideshow supports selectors, buttons, arrows, wrapping, photos and missing-photo fallback', async ({ page }) => {
  await page.goto('/tests/creators.html')
  await expect(page.getByRole('heading', { name: 'Fixture A' })).toBeVisible()
  await page.getByRole('button', { name: 'Creatore successivo' }).click()
  await expect(page.getByRole('heading', { name: 'Fixture B' })).toBeVisible()
  await expect(page.getByRole('img')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Example' })).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('heading', { name: 'Fixture C' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Grafica di prova' })).toBeVisible()
  await page.getByRole('button', { name: 'Creatore successivo' }).click()
  await expect(page.getByRole('heading', { name: 'Fixture A' })).toBeVisible()
  await page.getByRole('button', { name: 'Fixture B' }).click()
  await expect(page.getByRole('button', { name: 'Fixture B' })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Home')
  await expect(page.getByRole('heading', { name: 'Fixture A' })).toBeVisible()
  await page.keyboard.press('End')
  await expect(page.getByRole('heading', { name: 'Fixture C' })).toBeVisible()
  await page.getByRole('button', { name: 'Creatore precedente' }).click()
  await expect(page.getByRole('heading', { name: 'Fixture B' })).toBeVisible()
})

test('mobile touch and long creator text fit without clipping or layout shifts', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 360, height: 740 }, hasTouch: true })
  const page = await context.newPage()
  await page.goto('/tests/creators.html')
  const card = page.getByRole('region', { name: 'Chi ha creato Recapp' })
  const before = await card.boundingBox()
  await page.getByRole('button', { name: 'Fixture B' }).tap()
  await expect(page.getByRole('heading', { name: 'Fixture B' })).toBeVisible()
  const after = await card.boundingBox()
  expect(after!.height).toBeCloseTo(before!.height, 0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await context.close()
})

test('record FAQ interactions', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ viewport: { width: 960, height: 800 }, recordVideo: { dir: testInfo.outputPath('video'), size: { width: 960, height: 800 } } })
  const page = await context.newPage()
  await anonymous(page)
  await page.goto('/faq')
  await page.getByRole('button', { name: 'Che cos’è Recapp e a cosa serve?' }).click()
  await page.waitForTimeout(700)
  await page.getByRole('button', { name: 'Come si accede alla propria classe?' }).click()
  await page.waitForTimeout(700)
  await page.getByRole('button', { name: 'Come si accede alla propria classe?' }).click()
  await page.getByRole('button', { name: 'Tema: chiaro' }).click()
  await page.waitForTimeout(700)
  await context.close()
  await testInfo.attach('FAQ interactions', { path: await page.video()!.path(), contentType: 'video/webm' })
})


test('empty and single-profile collections need no carousel controls', async ({ page }) => {
  await page.goto('/tests/creators.html?empty')
  await expect(page.getByText('Le presentazioni personali dei creatori saranno aggiunte dal team.')).toBeVisible()
  await expect(page.getByRole('button')).toHaveCount(0)
  await page.goto('/tests/creators.html?single')
  await expect(page.getByRole('heading', { name: 'Fixture A' })).toBeVisible()
  await expect(page.getByRole('button')).toHaveCount(0)
})

test('creator slideshow remains usable with reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/tests/creators.html')
  await page.getByRole('button', { name: 'Fixture C' }).click()
  await expect(page.getByRole('heading', { name: 'Fixture C' })).toBeVisible()
  expect(await page.locator('.creator-slide[data-active="true"]').evaluate(el => getComputedStyle(el).transform)).toBe('none')
})

test('record creator component with synthetic test profiles', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ viewport: { width: 960, height: 800 }, recordVideo: { dir: testInfo.outputPath('video'), size: { width: 960, height: 800 } } })
  const page = await context.newPage()
  await page.goto('/tests/creators.html')
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'Creatore successivo' }).click()
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'Fixture C' }).click()
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'Creatore precedente' }).click()
  await page.waitForTimeout(600)
  await context.close()
  await testInfo.attach('Creator component (test fixtures)', { path: await page.video()!.path(), contentType: 'video/webm' })
})
